### ISSUE TITLE
Allow player to specify buy and sell prices in stations they own

### ISSUE THREAD

**Issue by stereoa** [masternerdguy/Open-Skies#1]

**Comment by masternerdguy** [comment]
Currently player owned stations use the same price calculation function as NPC owned stations. Player owned stations should allow the player to (optionally) manually set a buy and sell price on stations they control.

Care will need to be taken to avoid affecting the price calculation of non-Player property.

**Comment by masternerdguy** [comment]
I've finished implementing this feature, the player can now specify buy and sell prices for each ware their station deals in. The prices are also clamped between the market min and max prices. When the custom price is set to -1 (the default) the price is auto calculated.
![screenshot-outlier open skies](https://cloud.githubusercontent.com/assets/1137221/14975022/1cc8afc0-10cb-11e6-9043-a2788b8b4e8d.png)
